### ISSUE TITLE
Checking for if a ruleset has all required values

### ISSUE THREAD

**Issue by Filip-H** [pedroterzero/oxce-yaml-helper#10]
list of required values according to the ruleset refrence:

* [x] craftWeapons:
  * [x] launcher: (note: missing this will cause error on launch)
<br/>

* [x] soldierTransformations:
  * [x] allowedSoldierTypes:
    (note: missing this will cause the transformation to appear in the menu, but no soldier can undergo it)
<br/>

* [x] alienDeployments:
  * [x] data: (while not listed as a required value omitting it usually will cause a crash)
    * [x] lowQty:
    * [x] highQty:
    * [x] percentageOutsideUFO:
    * [x] itemSets: (note: only this seems to cause a crash when omitted)
<br/>
        
* [x] manufactureShortcut:
  * [x] startFrom: (i haven't tested what happens if the value is omitted)
<br/>

* [x] ufopaedia:
  * [x] type_id; (omitting it will cause the article not to appear)
  * [x] if a craft ufopaedia article has a text: but not a rect_text: the text won't appear, though missing it won't cause a crash, flagging it as a problem could help someone not realizing the issue
<br/>

* [x] alienMissions:
  * [x] waves: (i haven't tested what happens if the value is omitted)
    * [x] trajectory: (omitting this will cause error on launch)
  * [x] raceWeights: (not 100% sure what happens if omitted)
<br/>

**Comment by pedroterzero** [comment]
@Filip-H said:
> 1. if a craft ufopaedia article has a text: but not a rect_text: the text won't appear, though missing it won't cause a crash, flagging it as a problem could help someone not realizing the issue.

**Comment by pedroterzero** [comment]
All done I think!

**Comment by pedroterzero** [comment]
1. `percentageOutsideUfo` does not actually seem required, it apparently defaults to `0`  meaning it can be omitted safely (documentation seems wrong on this) -- so I think this check can be removed.
2.  `raceWeights`: this CAN cause a segfault if missing, but it also needs to check `missionScripts:` for it. It can be defined there too. It can be omitted from `alienMissions:` if it is in `missionScripts:`. Currently this leads to false positives

**Comment by pedroterzero** [comment]
* [ ] add test for keyreference type check

**Comment by pedroterzero** [comment]
Released in [v0.6.0](https://github.com/pedroterzero/oxce-yaml-helper/releases/tag/v0.6.0)
