### ISSUE TITLE
Non-existent firesound not flagged

### ISSUE THREAD

**Issue by Filip-H** [pedroterzero/oxce-yaml-helper#11]
Example:
https://github.com/Inventorum-Development-Team/IDT_UNEXCOM/blob/1b375a304ca27d5c8aea776718641e87bad040e3/Ruleset/BallisticWeapons_UNEXCOM.rul#L849

**Comment by pedroterzero** [comment]
@Filip-H I happened to already have fixed this in my local branch. It should now be correctly picked up in `0.4.0-rc2`.

Please let me know ;)

**Comment by pedroterzero** [comment]
Was closed and fixed
