### ISSUE TITLE
hitanimation flagged as non-existent while being defined

### ISSUE THREAD

**Issue by Filip-H** [pedroterzero/oxce-yaml-helper#23]
False positive here:
https://github.com/Inventorum-Development-Team/IDT_UNEXCOM/blob/1b375a304ca27d5c8aea776718641e87bad040e3/Ruleset/BallisticWeapons_UNEXCOM.rul#L648

Defined here:
https://github.com/Inventorum-Development-Team/IDT_UNEXCOM/blob/1b375a304ca27d5c8aea776718641e87bad040e3/Ruleset/BallisticWeapons_UNEXCOM.rul#L5378

**Comment by pedroterzero** [comment]
Solved in -rc3!
