### ISSUE TITLE
Global vars linking

### ISSUE THREAD

**Issue by Finnik723** [pedroterzero/oxce-yaml-helper#5]
global properties I can link, they all are linked to researches
mana - `unlockResearch`, `fakeUnderwaterBaseUnlockResearch`, `psiUnlockResearch` and `newBaseUnlockResearch` - those are OXC(E) and  `ufopaediaUnlockResearch`, `baseConstructionUnlockResearch` - those are FTA

**Comment by pedroterzero** [comment]
Added in 0.5.0
