### ISSUE TITLE
A duplicate is flagged when it shouldn't when a startingbase: has multiple facilities of the same type

### ISSUE THREAD

**Issue by Filip-H** [pedroterzero/oxce-yaml-helper#8]
Look at the 40k mod for an example

**Comment by pedroterzero** [comment]
@Filip-H I see I had caught this for `startingBase:` but not for:

* startingBaseBeginner
* startingBaseExperienced
* startingBaseVeteran
* startingBaseGenius
* startingBaseSuperhuman

Fixing in `0.4.0-alpha5`
