### ISSUE TITLE
Checking if an ufopaedia article that requires an image has image_id:

### ISSUE THREAD

**Issue by Filip-H** [pedroterzero/oxce-yaml-helper#9]
If an ufopaedia article that requires an image lacks image_id it results in a segfault,
type_ids probably affected by this are: 1, 2, 7, 11 and 12,

**Comment by pedroterzero** [comment]
From what I can see from the OXCE source code `1, 2, 3, 5, 7, 10, 11, 12, 13, 14, 15, 16, 17` need it, so only 4, 6, 8 and 9 don't.

That's how I added it anyway ;)
